apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: iga1playeconomy-host
spec:
  hostname: iga1playeconomy.eastus.cloudapp.azure.com
  acmeProvider:
    email: igor.clemente@aerosoftcargas.com.br
  tlsSecret:
    name: iga1playeconomy-tls
