apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: iga1dotapprentice-host
spec:
  hostname: iga1dotapprentice.eastus.cloudapp.azure.com
  acmeProvider:
    email: igor.clm20@gmail.com
  tlsSecret:
    name: iga1dotapprentice-tls
