apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iga1dotapprentice-tls-cert
spec:
  secretName: iga1dotapprentice-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "iga1dotapprentice.eastus.cloudapp.azure.com"
